{% set name = "pomegranate" %}
{% set version = "0.14.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pomegranate-{{ version }}.tar.gz
  sha256: 2296651290482dd53204ffaaaea267ceee057ce1b3ef1f9d9793febe66d6693d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython  # [target_platform != build_platform]
    - numpy   # [target_platform != build_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy >=0.17.0
  run:
    - joblib >=0.9.0b4
    - networkx >=2.4
    - {{ pin_compatible("numpy") }}
    - python
    - pyyaml
    - scipy >=0.17.0

test:
  imports:
    - pomegranate
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/pomegranate/
  doc_url: https://pomegranate.readthedocs.io
  dev_url: https://github.com/jmschrei/pomegranate
  summary: Pomegranate is a graphical models library for Python, implemented in Cython for speed.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - micknudsen
    - wolfv
