{% set name = "pomegranate" %}
{% set version = "0.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmschrei/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 24be72fe121c0bbe45d3eac8626de51f241022cb1929798a0b5a77b94144f317

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.22.1
    - numpy >=1.8.0
    - pip
    - python
    - scipy >=0.17.0
  run:
    - joblib >=0.9.0b4
    - networkx >=2.0
    - {{ pin_compatible("numpy") }}
    - python
    - pyyaml
    - scipy >=0.17.0

test:
  imports:
    - pomegranate
    - pomegranate.distributions

about:
  home: http://pypi.python.org/pypi/pomegranate/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pomegranate is a graphical models library for Python, implemented in Cython for speed.
  doc_url: https://pomegranate.readthedocs.io
  dev_url: https://github.com/jmschrei/pomegranate

extra:
  recipe-maintainers:
    - micknudsen
