{% set name = "pomegranate" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # The pomegranate pypi package is not up to date and points to the old Github repo
  url: https://github.com/jmschrei/pomegranate/archive/v{{ version }}.tar.gz
  sha256: 2cb49b7767b4a0059ec2801307ec6ee5b192e0f2ef8f33e2ed79b51d23b973a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.22.2
    - scipy >=1.6.2
    - scikit-learn >=1.0.2
    - pytorch >=1.9.0
    - apricot-select >=0.6.1
    - networkx >=2.8.4

test:
  imports:
    - pomegranate
    - pomegranate.bayes_classifier
    - pomegranate.bayesian_network
    - pomegranate.factor_graph
    - pomegranate.gmm
    - pomegranate.kmeans
    - pomegranate.markov_chain
    - pomegranate.distributions
    - pomegranate.hmm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmschrei/torchegranate
  doc_url: https://pomegranate.readthedocs.io
  dev_url: https://github.com/jmschrei/pomegranate
  summary: Pomegranate is a graphical models library for Python. Fast, flexible and easy to use probabilistic modelling in Python.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - micknudsen
    - wolfv
    - tschuelia
